package com.xxx.entity;

import java.io.Serializable;
import java.util.Date;

public class Booking implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_booking.id
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_booking.is_done
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    private Integer isDone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_booking.name
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_booking.content
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_booking.time
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_booking.count
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_booking.is_delete
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_booking.create_time
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_booking.level
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_booking.date
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_booking.id
     *
     * @return the value of tb_booking.id
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_booking.id
     *
     * @param id the value for tb_booking.id
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_booking.is_done
     *
     * @return the value of tb_booking.is_done
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public Integer getIsDone() {
        return isDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_booking.is_done
     *
     * @param isDone the value for tb_booking.is_done
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public void setIsDone(Integer isDone) {
        this.isDone = isDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_booking.name
     *
     * @return the value of tb_booking.name
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_booking.name
     *
     * @param name the value for tb_booking.name
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_booking.content
     *
     * @return the value of tb_booking.content
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_booking.content
     *
     * @param content the value for tb_booking.content
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_booking.time
     *
     * @return the value of tb_booking.time
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_booking.time
     *
     * @param time the value for tb_booking.time
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_booking.count
     *
     * @return the value of tb_booking.count
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_booking.count
     *
     * @param count the value for tb_booking.count
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_booking.is_delete
     *
     * @return the value of tb_booking.is_delete
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_booking.is_delete
     *
     * @param isDelete the value for tb_booking.is_delete
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_booking.create_time
     *
     * @return the value of tb_booking.create_time
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_booking.create_time
     *
     * @param createTime the value for tb_booking.create_time
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_booking.level
     *
     * @return the value of tb_booking.level
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_booking.level
     *
     * @param level the value for tb_booking.level
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_booking.date
     *
     * @return the value of tb_booking.date
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_booking.date
     *
     * @param date the value for tb_booking.date
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Booking other = (Booking) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIsDone() == null ? other.getIsDone() == null : this.getIsDone().equals(other.getIsDone()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getCount() == null ? other.getCount() == null : this.getCount().equals(other.getCount()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getDate() == null ? other.getDate() == null : this.getDate().equals(other.getDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIsDone() == null) ? 0 : getIsDone().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getCount() == null) ? 0 : getCount().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getDate() == null) ? 0 : getDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", isDone=").append(isDone);
        sb.append(", name=").append(name);
        sb.append(", content=").append(content);
        sb.append(", time=").append(time);
        sb.append(", count=").append(count);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", createTime=").append(createTime);
        sb.append(", level=").append(level);
        sb.append(", date=").append(date);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}