package com.xxx.mapper;

import com.xxx.entity.Booking;
import com.xxx.entity.BookingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    long countByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    int deleteByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    int insert(Booking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    int insertSelective(Booking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    List<Booking> selectByExample(BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    Booking selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    int updateByExampleSelective(@Param("record") Booking record, @Param("example") BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    int updateByExample(@Param("record") Booking record, @Param("example") BookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    int updateByPrimaryKeySelective(Booking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_booking
     *
     * @mbg.generated Thu Jan 26 09:25:12 CST 2023
     */
    int updateByPrimaryKey(Booking record);
}